### ISSUE TITLE
Decision Tree/Graph sample?

### ISSUE THREAD

**Issue by jtejido** [amidst/toolbox#100]
Hi,

Thanks for this great library. I'm wondering if the samples can be extended to include decision graph and/or automated decision selection? Is the library also open for extension like probabilistic programming?

**Comment by andresmasegosa** [comment]
Hi, 

decision graphs and automatic decision selection is not included in the library at the moment. The library is open in the sense it provides an API which is quite close to a probabilistic programming language: you can define random variables and relationships between them. The difference in Amidst is that we consider a restricted set of models where learning can be performed quite efficiently. There other frameworks like InferPy (https://inferpy.readthedocs.io), which allows to define much more general models, but at the expense of a more computationally heavy learning process.

**Comment by jtejido** [comment]
Thanks mate!
