### ISSUE TITLE
Travis-ci produces an error in LDA models in the tutorial module

### ISSUE THREAD

**Issue by andresmasegosa** [amidst/toolbox#43]
Travis-ci produces an error in LDA models in the tutorial module. They do not appear when runs locally. They are deactivated now.

**Comment by andresmasegosa** [comment]
Tests for tutorial module are skipped. I can not understand why do not passed (they are killed by travis-ci). They passed on the tutorial repository. Problems are due too flink.

**Comment by rcabanasdepaz** [comment]
They are now passed: https://s3.amazonaws.com/archive.travis-ci.org/jobs/166498964/log.txt
