### ISSUE TITLE
Can amidst learn structure from data automaticlly?

### ISSUE THREAD

**Issue by liyi193328** [amidst/toolbox#49]
Hello, 
     guys, 
     I want to know whether amidst can **learn structure from data automatically**; And
     According to document, when new batch data comes, there is a way can update the paraments of bayesian network incremently; But I want to know whether **the structure of network change because of paraments' change.** 
     Thanks.

**Comment by andresmasegosa** [comment]
Hi, 

Thanks for you interest.

Unfortunately, we do not cover structural learning.  Now, Amidst is based on parameter learning. The key is that **your structure can contain latent/hidden variables**. Moreover, parameter learning can be performed in a **incremental way**.
