### ISSUE TITLE
Query: DynamicDataStream

### ISSUE THREAD

**Issue by gunjanthesystem** [amidst/toolbox#75]
Hi,

Could you kindly help me with the following doubt.
 
 Why in the DynamicDataStream example, i.e., "https://github.com/amidst/toolbox/blob/master/examples/src/main/java/eu/amidst/dynamic/examples/datastream/DataStreamsExample.java", only the first sequence, i.e. sequence id = 0 is being traversed in loop in line 48 ? 

I would have expected it to go over all the 1000 entries in the dataset but it is only going over the 50 entries of first sequence. On the other hand, data.stream().count() returns 1000 which is congruent with my expectation. I guess I am missing out something here.

Thanks

**Comment by andresmasegosa** [comment]
Hi, 

Yes you are right, this is a bug. I know how to fix it. 

Thanks,
