### ISSUE TITLE
The probability distributions remain uniform

### ISSUE THREAD

**Issue by gowthamnatarajan** [amidst/toolbox#81]
The probability distributions for variable without a parent remains a uniform distribution. It does not learn the marginal probability from the data.

**Comment by andresmasegosa** [comment]
Hi, 

could you provide more details, please?

**Comment by gowthamnatarajan** [comment]
I looked deeper into the model and found that ALL probabilities (marginal and conditional) is uniform. That is its all 0.5 if it has 2 states or all are 0.333 if it has 3 states and so on at **Time 0** only. 
The probabilities at Time T all probabilities are correct. Weird!! Why is that??

Should I create a dynamicDag separately for Time 0 and Time T?

**Comment by andresmasegosa** [comment]
How is the training data you are using? is it composed of a single sequence with many time steps?

**Comment by gowthamnatarajan** [comment]
Many sequences and many time steps

**Comment by gowthamnatarajan** [comment]
Many sequences and many time steps.

**Comment by andresmasegosa** [comment]
Could you please share the piece of code you are running? Just to know which learning algorithm you are using and how you use it.

**Comment by gowthamnatarajan** [comment]
I found the issue. The TIME_ID for every sequence was starting at 1 and not 0.
In the example data-sets too it was starting at 1. Can some new examples be added which start at 0?
