### ISSUE TITLE
Mark some variables as non temporal

### ISSUE THREAD

**Issue by gowthamnatarajan** [amidst/toolbox#84]
Is there a way to mark certain variables as non temporal? That is, their value does not change and remains the same as it was at Time 0.

**Comment by andresmasegosa** [comment]
Not really, this is also a nice extension. Mixing temporal and non-temporal variables. 

But you can easily simulate these settings by using standard temporal variables which do not depend on any variable in the previous time step. When providing evidence you copy the value from Time 0 to all the following time steps.

**Comment by gowthamnatarajan** [comment]
Ok. But while generating samples, the value of non temporal variables keeps changing. This is another use case

**Comment by andresmasegosa** [comment]
OK. I think I get your point. I propose you the following hack:

a) Define your variable X at time 0 as you like. 

b) Define you variable X_t conditioned to X_t-1 and hard code a deterministic relationship. E.g. if X_t is binary then p(x_t=0|x_t-1 = 0) = 1, p(x_t=1|x_t-1 = 0) = 0, p(x_t=0|x_t-1 = 1) = 0 and p(x_t=1|x_t-1 = 1) = 1. 

Then, the sampled value at time 0 will not change in the time sequence.
