### ISSUE TITLE
Supply already trained model to ParallelMaximumLikelihood

### ISSUE THREAD

**Issue by gowthamnatarajan** [amidst/toolbox#85]
Is it possible to update an already existing Bayesian network with new data while using maximum likelihood algorithm? I don't see and option to pass an existing network as a parameter.

**Comment by andresmasegosa** [comment]
Yes, this is possible. You should use the "update" method. Consider the following example:

        ParameterLearningAlgorithm parallelMaximumLikelihood = new ParallelMaximumLikelihood();
        parallelMaximumLikelihood.setWindowsSize(1000);
        parallelMaximumLikelihood.setDynamicDAG(dbnRandom.getDynamicDAG());
        parallelMaximumLikelihood.initLearning();
        parallelMaximumLikelihood.updateModel(data);

        DynamicBayesianNetwork dbnLearnt = parallelMaximumLikelihood.getLearntDBN();
        
        parallelMaximumLikelihood.updateModel(newdata);

        DynamicBayesianNetwork dbnLearntUpdated = parallelMaximumLikelihood.getLearntDBN();

**Comment by gowthamnatarajan** [comment]
The object parallelMaximumLikelihood should be serialised by me? Once the first model is trained, the program exits. Later I want the parallelMaximumLikelihood to start from the old model.
In the above example after the first call to getLearntDbn, the program exits. After a few days I want to continue.

**Comment by andresmasegosa** [comment]
Yes, this is a hack you can use to avoid this problem.
