### ISSUE TITLE
Missing `./datasets/simulated/bank_data_train.arff` file

### ISSUE THREAD

**Issue by mohataher** [amidst/toolbox#93]
Great repo. On [InferenceDemo](https://github.com/amidst/toolbox/blob/87a7ab1cb5150fea1a063729ba981cd64157c793/huginlink/src/main/java/eu/amidst/huginlink/examples/demos/InferenceDemo.java#L71), there was a reference to `./datasets/simulated/bank_data_train.arff` file. I cannot find this file in the repo, tried to find it in git history and it doesn't seem to exist as well. 

Have you commit this file?

**Comment by rcabanasdepaz** [comment]
Thank you for your collaboration. Along this week we will publish a new release with this dataset.
