### ISSUE TITLE
Paper explaning the model in DynamicNaiveBayesClassifier

### ISSUE THREAD

**Issue by mohataher** [amidst/toolbox#94]
Hi, it seems like the class [`DynamicNaiveBayesClassifier`](https://github.com/amidst/toolbox/blob/012c8fd92b950f8fc7bcf6cd6644925acb15a60c/core-dynamic/src/main/java/eu/amidst/dynamic/learning/parametric/DynamicNaiveBayesClassifier.java) misses any sort of scientific documentation. There are plenty of papers discussing dynamic naive bayesian classification approaches which makes it really difficult to find it using Google. 

It would be great to add a reference to its corresponding paper in the JavaDoc.

**Comment by mohataher** [comment]
It seems like this [presentation](http://amidst.eu/upload/dokumenter/Presentations/scai2015.pdf) by Hanen Borchani on SCAI 2015 discusses that algorithm. Is this true?

**Comment by andresmasegosa** [comment]
A suitable reference would be this one:

Murphy, Kevin P. "Dynamic bayesian networks." Probabilistic Graphical Models, M. Jordan 7 (2002).

Think that a Dynamic NB classifier is a standard naives Bayes classifier where the class variable is connected over time. By inspecting the dynamic graph created by AMIDST you can observe that. 

We'll include this reference in the documentation in the next release.
